Homework 1
================
Mayuri Albal
2022-09-18

## Problem 1

``` r
data("penguins", package = "palmerpenguins")
```

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean.default(penguins$flipper_length_mm, na.rm = TRUE)
```

    ## [1] 200.9152

In this data set, there are 8 variables and 344 observations for
penguins. The variables include:species, island, length of bill (mm),
depth of bill (mm), flipper length (mm), body mass (g), sex, and year of
birth? The mean flipper length of penguins in the data set is 200.92 mm.
